### ISSUE TITLE
Publish fails on Windows

### ISSUE THREAD

**Issue by kn-ivan** [debashish2014/local-package-publisher#5]
When I try to publish on Windows, I get `no such file or directory` errors.  I'm guessing this is a path issue, where somehow it's not recognizing the OS and not converting /'s to \'s or something?  

The specific error is:
```
C:\Users\{userName}\AppData\Roaming\npm/node: line 8: C:\Users\{userName}\AppData\Roaming\npm/node_modules/node/bin/node: No such file or directory
```

Windows 11 Pro; version 10.0.22000 Build 22000

Is there a workaround for this?

**Comment by debashish2014** [comment]
Hi @kn-ivan, I'm sorry for the delay in fixing the issue. I was not getting time to maintain this project because of other projects' workloads. This issue has been resolved in version 1.0.5. Can you please try this version and share your thoughts?

I just wanted to let you know that I'm closing the issue for now.

Please feel free to re-open the issue if the problem still persists.
